version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php74:
    build: .
    image: heimdall:p74
    container_name: heimdall
    privileged: false
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    tty: true
    ports:
      - 31742:80
